spring.application.name=Rural-Animal
spring.datasource.url=jdbc:mysql://shinkansen.proxy.rlwy.net:21406/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=xuausXXHyrQUiGJchxEPzadtixTBZJPB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
security.jwt.expiration-time=3600000

implementation 'org.springframework.boot:spring-boot-starter-mail'
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ruralanimalcr@gmail.com
spring.mail.password=${EmailPassword}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Gemini API Configuration
gemini.api-key=${GEMINI_API_KEY:AIzaSyBm32jn8JBnDZBK2W20Yklx_X1VoQBjQuo}
gemini.model=gemini-2.5-flash


spring.security.oauth2.client.registration.google.client-id=46886143065-s5628d3fhn7govkol2lff7qclqklutc4.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile,https://www.googleapis.com/auth/calendar
frontend.url=http://localhost:4200
app.cors.allowed-origins=http://localhost:4200,http://127.0.0.1:4200
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.client-authentication-method=client_secret_basic
google.calendar-id=dc8203157160c5d41bb59dfd5f525fcf8b2aea5d21330e228280fe1b73fbb1f3@group.calendar.google.com


paypal.client.id=AfHSBCj5PVyUjkpAQB8NjMSkef5w2lIy9Z8vMIXLBKH705PMdeqUyQHAYlYmhEOFCqZgd2u_eK9_GPdO
paypal.client.secret=EJehE6wQlCVlK_P-Q-AVluQ4faAjso5KEXahE_HFV-6N_DEEhh8w2vjNmTy35rdfPg6nWebvHH7y2R15
paypal.mode=sandbox

exchange.rate.api.key=d826df9ae88282af9333d13d
exchange.rate.api.url=https://v6.exchangerate-api.com/v6/${exchange.rate.api.key}/latest/USD


spring.data.redis.host=localhost
spring.data.redis.port=6379
