name: CI Quality Pipeline

on:
  push:
    branches: [ "pipeline-test" ]
  pull_request:
    branches: [ "pipeline-test" ]

jobs:
  tests-coverage-and-sonarcloud:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11
        env:
          MARIADB_ROOT_PASSWORD: 12345
          MARIADB_DATABASE: proyecto3_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mariadb-admin ping -h 127.0.0.1 -uroot -p12345"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Dar permisos a gradlew
        run: chmod +x gradlew

      - name: Ejecutar pruebas unitarias
        run: ./gradlew clean unitTest

      - name: Ejecutar pruebas API
        env:
          SPRING_PROFILES_ACTIVE: test
          SPRING_DATASOURCE_URL: jdbc:mariadb://localhost:3306/proyecto3_test
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: 12345
        run: ./gradlew apiTest

      - name: Generar cobertura JaCoCo
        run: ./gradlew jacocoTestReport

      - name: Ejecutar análisis en SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar